<?php
use Magento\Framework\App\Action\Action;

if ($this->helper('Tiendamia\Deals\Helper\Data')->isActive()) {


    $_productCollectionStore1 = $block->getLoadProducts($this->helper('Tiendamia\Deals\Helper\Data')->getCatId(1)); // Argentina
    $_productCollectionStore2 = $block->getLoadProducts($this->helper('Tiendamia\Deals\Helper\Data')->getCatId(2)); // Uruguay
    $_productCollectionStore3 = $block->getLoadProducts($this->helper('Tiendamia\Deals\Helper\Data')->getCatId(3)); // Chile


    $_helper = $this->helper('Magento\Catalog\Helper\Output');


    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $pos = $block->getPositioned();

    $pos = !empty($pos) ? $pos : '';
    $viewMode = !empty($viewMode) ? $viewMode : '';

    $position = '';
    $formKey = $block->getFormKey();
    $title = $this->helper('Tiendamia\Deals\Helper\Data')->getTitlePage();
    $dueDate = $this->helper('Tiendamia\Deals\Helper\Data')->getDueDate();
    ?>

    <div data-content-type="row" data-appearance="contained" data-element="main">
        <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-element="inner"
             style="justify-content: flex-start; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;">
            <div data-content-type="html" data-appearance="default" data-element="main"
                 style="border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 0px;"
                 data-decoded="true">

                <div class="align-center">
                    <div class="not-mobile">

                        <img class="banner-1500px main_banner_bg"
                             style="background: linear-gradient(to bottom, #76baf6, #76baf6);"
                             src="<?php echo $this->getViewFileUrl('Tiendamia_Deals::images/banner-header.png'); ?>"/>

                    </div>
                </div>

                <h2>
                    <center><?php echo $title; ?></center>
                </h2>

                <div class="flip-clock">
                <span class="flip-clock__title" style="">
                    <span class="flip-clock__card flip-card">
                        <b class="flip-card__top" style="width: 4.8em;background: transparent;">QUEDAN</b>
                    </span>
                    <span class="flip-clock__slot">&nbsp;</span>
                </span>
                    <span class="flip-clock__piece" style="">
                  <span class="flip-clock__card flip-card">
                      <b class="flip-card__top" id="dias">00</b>
                    </span>
                    <span class="flip-clock__slot">Días</span>
                  </span>
                    <span class="flip-clock__piece flip" style="">
                    <span class="flip-clock__card flip-card">
                      <b class="flip-card__top" id="horas">23</b>
                    </span>
                    <span class="flip-clock__slot">Horas</span>
                  </span>
                    <span class="flip-clock__piece flip" style="">
                    <span class="flip-clock__card flip-card">
                      <b class="flip-card__top" id="minutos">21</b>
                    </span>
                    <span class="flip-clock__slot">Minutos</span>
                  </span>
                    <span class="flip-clock__piece flip" style="">
                    <span class="flip-clock__card flip-card">
                      <b class="flip-card__top" id="segundos">26</b>
                    </span>
                    <span class="flip-clock__slot">Segundos</span>
                 </span>
                </div>


                <!--            // slide1-->
                <h2>Mas comprados en Argentina</h2>
                <?php $count = 1; ?>
                <div class="ind-container">
                    <div class=" products wrapper grid products-grid <?php /* @escapeNotVerified */
                    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
                    echo $viewMode; ?>">
                        <?php $iterator = 1; ?>
                        <div class="products grid items product-items slick-carousel slide1">
                            <?php $prdCount = 0; ?>
                            <?php if (!empty($_productCollectionStore1->getItems())): ?>
                                <?php foreach ($_productCollectionStore1 as $_product):

                                    ?>
                                    <?php $_product = $block->getLoadProduct($_product->getEntityId()); ?>
                                    <div class="item product product-item">
                                        <div class="product-item-info item" data-container="product-grid">
                                            <?php
                                            $productImage = $block->getImage($_product, $image);
                                            if ($pos != null) {
                                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                                    . 'top:' . $productImage->getHeight() . 'px;"';
                                            }
                                            ?>
                                            <?php // Product Image
                                            ?>
                                            <a href="<?php /* @escapeNotVerified */
                                            echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                               tabindex="-1">
                                                <?php /* @escapeNotVerified */
                                                echo $productImage->toHtml(); ?>
                                            </a>
                                            <div class="product details product-item-details">
                                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                                <strong class="product name product-item-name">
                                                    <a class="product-item-link"
                                                       href="<?php /* @escapeNotVerified */
                                                       echo $_product->getProductUrl() ?>">
                                                        <?php /* @escapeNotVerified */
                                                        echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                    </a>
                                                </strong>
                                                <?php /* @escapeNotVerified */
                                                echo $block->getProductPrice($_product); ?>
                                                <?php /* @escapeNotVerified */
                                                echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

                                                <div class="product-item-inner">
                                                    <div
                                                        class="product actions product-item-actions"<?php /* @escapeNotVerified */
                                                    echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                        <div class="actions-primary"<?php /* @escapeNotVerified */
                                                        echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                            <?php if ($_product->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                                      method="post"
                                                                >
                                                                    <input type="hidden"
                                                                           name="product"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data']['product'] ?>">
                                                                    <input type="hidden"
                                                                           name="<?= /* @noEscape */
                                                                           Action::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?=
                                                                           /* @noEscape */
                                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                                           ?>">
                                                                    <input type="hidden" name="form_key"
                                                                           value="<?= /* @noEscape */
                                                                           $formKey ?>">

                                                                    <button type="submit"
                                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product->getIsSalable()): ?>
                                                                    <div class="stock available">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <script type="text/x-magento-init">
                        {
                            "[data-role=tocart-form], .form.map.checkout": {
                                "catalogAddToCart": {
                                    "product_sku": "<?= /* @noEscape */
                                            $_product->getSku() ?>"
                                }
                            }
                        }


                                        </script>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php $count++; ?>


                <!--            // slide 2-->
                <h2>Mas comprados en Uruguay</h2>
                <?php $count = 1; ?>
                <div class="ind-container">
                    <div class=" products wrapper grid products-grid <?php /* @escapeNotVerified */
                    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
                    echo $viewMode; ?>">
                        <?php $iterator = 1; ?>
                        <div class="products grid items product-items slick-carousel slide2">
                            <?php $prdCount = 0; ?>
                            <?php if (!empty($_productCollectionStore2->getItems())): ?>
                                <?php foreach ($_productCollectionStore2 as $_product2):

                                    ?>
                                    <?php $_product2 = $block->getLoadProduct($_product2->getEntityId()); ?>
                                    <div class="item product product-item">
                                        <div class="product-item-info item" data-container="product-grid">
                                            <?php
                                            $productImage = $block->getImage($_product2, $image);
                                            if ($pos != null) {
                                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                                    . 'top:' . $productImage->getHeight() . 'px;"';
                                            }
                                            ?>
                                            <?php // Product Image
                                            ?>
                                            <a href="<?php /* @escapeNotVerified */
                                            echo $_product2->getProductUrl() ?>"
                                               class="product photo product-item-photo"
                                               tabindex="-1">
                                                <?php /* @escapeNotVerified */
                                                echo $productImage->toHtml(); ?>
                                            </a>
                                            <div class="product details product-item-details">
                                                <?php $_productNameStripped = $block->stripTags($_product2->getName(), null, true); ?>
                                                <strong class="product name product-item-name">
                                                    <a class="product-item-link"
                                                       href="<?php /* @escapeNotVerified */
                                                       echo $_product2->getProductUrl() ?>">
                                                        <?php /* @escapeNotVerified */
                                                        echo $_helper->productAttribute($_product2, $_product2->getName(), 'name'); ?>
                                                    </a>
                                                </strong>
                                                <?php /* @escapeNotVerified */
                                                echo $block->getProductPrice($_product2); ?>
                                                <?php /* @escapeNotVerified */
                                                echo $block->getReviewsSummaryHtml($_product2, $templateType); ?>

                                                <div class="product-item-inner">
                                                    <div
                                                        class="product actions product-item-actions"<?php /* @escapeNotVerified */
                                                    echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                        <div class="actions-primary"<?php /* @escapeNotVerified */
                                                        echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                            <?php if ($_product2->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_product2); ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $escaper->escapeHtml($_product2->getSku()) ?>"
                                                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                                      method="post"
                                                                >
                                                                    <input type="hidden"
                                                                           name="product"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data']['product'] ?>">
                                                                    <input type="hidden"
                                                                           name="<?= /* @noEscape */
                                                                           Action::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?=
                                                                           /* @noEscape */
                                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                                           ?>">
                                                                    <input type="hidden" name="form_key"
                                                                           value="<?= /* @noEscape */
                                                                           $formKey ?>">

                                                                    <button type="submit"
                                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product2->getIsSalable()): ?>
                                                                    <div class="stock available">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <script type="text/x-magento-init">
                        {
                            "[data-role=tocart-form], .form.map.checkout": {
                                "catalogAddToCart": {
                                    "product_sku": "<?= /* @noEscape */
                                            $_product2->getSku() ?>"
                                }
                            }
                        }


                                        </script>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php $count++; ?>


                <!--            //slide3-->
                <h2>Mas comprados en Chile</h2>
                <?php $count = 1; ?>
                <div class="ind-container">
                    <div class=" products wrapper grid products-grid <?php /* @escapeNotVerified */
                    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
                    echo $viewMode; ?>">
                        <?php $iterator = 1; ?>
                        <div class="products grid items product-items slick-carousel slide3">
                            <?php $prdCount = 0; ?>
                            <?php if (!empty($_productCollectionStore3->getItems())): ?>
                                <?php foreach ($_productCollectionStore3 as $_product3):

                                    ?>
                                    <?php $_product3 = $block->getLoadProduct($_product3->getEntityId()); ?>
                                    <div class="item product product-item">
                                        <div class="product-item-info item" data-container="product-grid">
                                            <?php
                                            $productImage = $block->getImage($_product3, $image);
                                            if ($pos != null) {
                                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                                    . 'top:' . $productImage->getHeight() . 'px;"';
                                            }
                                            ?>
                                            <?php // Product Image
                                            ?>
                                            <a href="<?php /* @escapeNotVerified */
                                            echo $_product3->getProductUrl() ?>"
                                               class="product photo product-item-photo"
                                               tabindex="-1">
                                                <?php /* @escapeNotVerified */
                                                echo $productImage->toHtml(); ?>
                                            </a>
                                            <div class="product details product-item-details">
                                                <?php $_productNameStripped = $block->stripTags($_product3->getName(), null, true); ?>
                                                <strong class="product name product-item-name">
                                                    <a class="product-item-link"
                                                       href="<?php /* @escapeNotVerified */
                                                       echo $_product3->getProductUrl() ?>">
                                                        <?php /* @escapeNotVerified */
                                                        echo $_helper->productAttribute($_product3, $_product3->getName(), 'name'); ?>
                                                    </a>
                                                </strong>
                                                <?php /* @escapeNotVerified */
                                                echo $block->getProductPrice($_product3); ?>
                                                <?php /* @escapeNotVerified */
                                                echo $block->getReviewsSummaryHtml($_product3, $templateType); ?>

                                                <div class="product-item-inner">
                                                    <div
                                                        class="product actions product-item-actions"<?php /* @escapeNotVerified */
                                                    echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                        <div class="actions-primary"<?php /* @escapeNotVerified */
                                                        echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                            <?php if ($_product3->isSaleable()): ?>
                                                                <?php $postParams = $block->getAddToCartPostParams($_product3); ?>
                                                                <form data-role="tocart-form"
                                                                      data-product-sku="<?= $escaper->escapeHtml($_product3->getSku()) ?>"
                                                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                                      method="post"
                                                                >
                                                                    <input type="hidden"
                                                                           name="product"
                                                                           value="<?= /* @noEscape */
                                                                           $postParams['data']['product'] ?>">
                                                                    <input type="hidden"
                                                                           name="<?= /* @noEscape */
                                                                           Action::PARAM_NAME_URL_ENCODED ?>"
                                                                           value="<?=
                                                                           /* @noEscape */
                                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                                           ?>">
                                                                    <input type="hidden" name="form_key"
                                                                           value="<?= /* @noEscape */
                                                                           $formKey ?>">

                                                                    <button type="submit"
                                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="action tocart primary">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                </form>
                                                            <?php else: ?>
                                                                <?php if ($_product3->getIsSalable()): ?>
                                                                    <div class="stock available">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable">
                                                                    <span><?php /* @escapeNotVerified */
                                                                        echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <script type="text/x-magento-init">
                        {
                            "[data-role=tocart-form], .form.map.checkout": {
                                "catalogAddToCart": {
                                    "product_sku": "<?= /* @noEscape */
                                            $_product3->getSku() ?>"
                                }
                            }
                        }


                                        </script>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php $count++; ?>
            </div>
        </div>
    </div>


    <script>
        require(['jquery', 'dealspage'], function ($, dealspage) {
            dealspage('<?php echo $dueDate; ?>');
        });
    </script>
    <?php
}
else {
    ?><p style="font-size: 15px;text-align: center;"><?php echo $this->helper('Tiendamia\Deals\Helper\Data')->showDisabledMessage();?></p><?php
}
?>
